{ pkgs, inputs, ... }:

let
  fenix = inputs.fenix.packages.${pkgs.system};

  # `fenix.latest` reads "whatever nightly is newest", but it is NOT a
  # floating reference in practice: it resolves against the fenix input
  # pinned in devenv.lock (rev d551111f, 2026-05-12), which currently
  # yields nightly 2026-05-11 — rustc 1.97.0-nightly (64a965e90),
  # clippy 0.1.97. Two people on this lock get the same compiler.
  #
  # The catch, and the reason for this comment: that pin is implicit and
  # lives in a file nobody reads. Updating devenv.lock changes the
  # compiler AND THE LINT SET. `cargo clippy --all-targets` exiting 0 is
  # the tree's answer to "is clippy clean?", so a routine lock bump can
  # turn that answer red without anyone touching a line of Rust.
  #
  # If you bump the lock, re-run BOTH clippy invocations from
  # scripts/ci-local.sh afterwards and fix or triage whatever new lints
  # land, in that change:
  #   cargo clippy --all-targets --all-features -- -D warnings
  #   cargo clippy --all-targets --no-default-features -- -D warnings
  #
  # (Pinning a dated nightly explicitly here — fenix.toolchainOf with
  # channel/date/sha256 — is the more self-documenting option, but it
  # requires carrying a toolchain hash that has to be regenerated by
  # hand on every bump. The lock already provides the reproducibility;
  # what was missing was the warning, so that is what this is.)
  rustToolchain = fenix.combine [
    fenix.latest.cargo
    fenix.latest.rustc
    fenix.latest.rust-src
    fenix.latest.clippy
    fenix.latest.rustfmt
  ];
in
{
  packages = [
    rustToolchain
    pkgs.pkg-config
    pkgs.openssl
    pkgs.sqlite
    pkgs.gcc
  ];

  env = {
    OPENSSL_NO_VENDOR = "1";
    RUST_BACKTRACE = "1";
  };

  enterShell = ''
    echo "beads_rust dev shell — $(rustc --version)"
  '';
}
