#!/usr/bin/env bash
# generate-e2e-matrix.sh — regenerate docs/E2E_COVERAGE_MATRIX.md from the
# command list `br capabilities` reports and the test files under tests/.
#
# Coverage is measured two ways per top-level command:
#   dedicated  a tests/e2e_<command>*.rs binary exists (hyphens become underscores)
#   mentions   number of tests/*.rs files that invoke the command by name
#              (`"<command>"` as a CLI argument literal)
# Status: covered = dedicated file or >= 3 mentioning files; partial = 1-2
# mentioning files; none = 0.
#
# Usage: scripts/generate-e2e-matrix.sh [--check]
#   --check   write to a temp file and diff against the committed matrix (exit 1 on drift)
set -euo pipefail
root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$root"
BR=${BR:-br}
export RUST_LOG=${RUST_LOG:-error}
OUT=docs/E2E_COVERAGE_MATRIX.md
MODE=${1:-}

commands=$("$BR" capabilities --format json | jq -r '.commands[].name' | sort)
[ -n "$commands" ] || { echo "generate-e2e-matrix: br capabilities returned no commands" >&2; exit 2; }
version=$("$BR" --version | awk '{print $2}')

tmp=$(mktemp "${TMPDIR:-/tmp}/e2e-matrix-XXXXXX.md")
{
  echo "# E2E Coverage Matrix - br CLI Commands"
  echo
  echo "> Generated by \`scripts/generate-e2e-matrix.sh\` from \`br capabilities\` ($version) and \`tests/*.rs\` on $(date -u +%F)."
  echo "> Do not edit by hand; re-run the script. \`--check\` diffs against this file."
  echo
  echo "| Command | Dedicated e2e file(s) | Test files mentioning it | Status |"
  echo "|---|---|---|---|"
  covered=0; partial=0; none=0; total=0
  while IFS= read -r cmd; do
    [ -n "$cmd" ] || continue
    total=$((total+1))
    snake=${cmd//-/_}
    dedicated=""
    for f in tests/e2e_"${snake}"*.rs; do
      [ -e "$f" ] || continue
      dedicated="${dedicated:+$dedicated }${f#tests/}"
    done
    mentions=$( { grep -lE "\"${cmd}\"" tests/*.rs 2>/dev/null || true; } | wc -l | tr -d ' ')
    if [ -n "$dedicated" ] || [ "$mentions" -ge 3 ]; then status=covered; covered=$((covered+1));
    elif [ "$mentions" -ge 1 ]; then status=partial; partial=$((partial+1));
    else status=none; none=$((none+1)); fi
    echo "| \`$cmd\` | ${dedicated:--} | $mentions | $status |"
  done <<< "$commands"
  echo
  echo "## Summary"
  echo
  echo "| Total commands | Covered | Partial | None |"
  echo "|---|---|---|---|"
  echo "| $total | $covered | $partial | $none |"
  echo
  echo "Commands with status \`none\` or \`partial\` are tracked as e2e gaps in the"
  echo "bridge plan (\`beads_rust-zxfz.4\`). A dedicated file is the preferred form"
  echo "of coverage; mention counts are a floor, not proof of behavior coverage."
} > "$tmp"

if [ "$MODE" = "--check" ]; then
  if diff -u "$OUT" "$tmp" >/dev/null; then
    echo "generate-e2e-matrix: $OUT is up to date"
    exit 0
  fi
  echo "generate-e2e-matrix: $OUT is out of date; regenerate with scripts/generate-e2e-matrix.sh" >&2
  diff -u "$OUT" "$tmp" | head -40 >&2 || true
  exit 1
fi
mv "$tmp" "$OUT"
echo "generate-e2e-matrix: wrote $OUT ($total commands)"
